### ISSUE TITLE
[Bug] Unable to Complete Communicate using Markdown 

### ISSUE THREAD

**Issue by jules946** [skills/communicate-using-markdown#135] opened 2024-05-10 09:07 UTC
### Discussed in https://github.com/orgs/skills/discussions/569

<div type='discussions-op-text'>

<sup>Originally posted by **Yash-Shindey** May  8, 2024</sup>
<img width="630" alt="Screenshot 2024-05-08 at 3 14 41 PM" src="https://github.com/skills/.github/assets/96872207/e8808ec3-168c-420b-be41-15b91de65c08">

Hey guys. I have done all the steps required and have published the page here https://exp-communicate-using-markdown-cohort-1.github.io/series-communicate-using-markdown-Yash-Shindey/  I am still unable to mark it as complete. Any help will be highly appreciated</div>

I am also experiencing the same issue. 

Repo: https://github.com/Exp-Communicate-Using-Markdown-Cohort-1/series-communicate-using-markdown-jules946
![image](https://github.com/skills/.github/assets/114394404/8897e089-d59c-4314-ab75-ee8e68ad1f6f)
![image](https://github.com/skills/.github/assets/114394404/33598f52-abd8-45bb-8f5e-9cea3c0083b1)

**Comment by hectorsector** [comment] 2024-05-22 15:45
Thanks so much for the report, @jules946. I've alerted the team that looks after GitHub Classroom about the problems and they're working on it. Since the problem isn't specific to Skills, I'll close this issue out but please reopen or reach out to support if it's not resolved soon.

**Closed by hectorsector** 2024-05-22 15:45 UTC
Labels: bug
